/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      overflow: {
        overlay: "overlay",
      },
      scrollbarGutter: {
        stable: "stable",
      },
      colors: {
        "on-tertiary-fixed-variant": "#00513e",
        "surface-container-highest": "#e2e2e9",
        "outline": "#737686",
        "surface": "#f9f9ff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#00174b",
        "surface-container-low": "#f3f3fa",
        "on-primary-container": "#fefcff",
        "inverse-surface": "#2e3036",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ffb3b0",
        "on-primary": "#ffffff",
        "surface-dim": "#d9d9e0",
        "secondary": "#ae2f34",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#003ea7",
        "error": "#ba1a1a",
        "tertiary-container": "#008467",
        "inverse-primary": "#b4c5ff",
        "tertiary": "#006951",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002117",
        "surface-container": "#ededf4",
        "on-surface": "#1a1c20",
        "on-secondary-fixed": "#410006",
        "on-secondary-fixed-variant": "#8c1520",
        "on-secondary-container": "#6d0010",
        "on-background": "#1a1c20",
        "tertiary-fixed-dim": "#3edeb2",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f5fff8",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-fixed": "#ffdad8",
        "surface-container-high": "#e8e7ef",
        "on-surface-variant": "#434654",
        "surface-variant": "#e2e2e9",
        "secondary-container": "#ff6b6b",
        "on-error": "#ffffff",
        "outline-variant": "#c3c6d7",
        "background": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "primary": "#0451d3",
        "primary-container": "#356ced",
        "tertiary-fixed": "#63fbcd",
        "surface-tint": "#0d54d6",
        "inverse-on-surface": "#f0f0f7"
      },
      fontFamily: {
        sans: [
          "Inter", // chính
          "Noto Sans JP", // tiếng Nhật
          "Helvetica Neue",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        mplus: ['"M PLUS 1p"', "sans-serif"],
        "body-md": ["Inter"],
        "japanese-display": ["Noto Sans JP"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "japanese-body": ["Noto Sans JP"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "japanese-display": ["40px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "japanese-body": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
